services:
  - type: web
    name: virtual-dost-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
